language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - if [ $(phpenv global) = "5.5" ]; then composer install --ignore-platform-reqs --prefer-source && composer update --prefer-lowest --prefer-stable -n; else composer --prefer-source install; fi;

script:
  - vendor/bin/phpunit
  - bin/psalm
